### ISSUE TITLE
Implement !when command

### ISSUE THREAD

**Issue by atiaxi** [smashwilson/pushbot#132]
In no particular order:

![friday](https://user-images.githubusercontent.com/13645/35175029-ce6be492-fd3f-11e7-9dba-ea3ffc6982c4.png)

![monday](https://user-images.githubusercontent.com/13645/35175030-ce7b6034-fd3f-11e7-851b-39b28602ff89.png)

![saturday](https://user-images.githubusercontent.com/13645/35175031-ce8d88e0-fd3f-11e7-8f85-64e4fcd04b91.png)
![sunday](https://user-images.githubusercontent.com/13645/35175032-cea2a374-fd3f-11e7-8009-9217789c6a4a.png)
![thursday](https://user-images.githubusercontent.com/13645/35175033-cebaa672-fd3f-11e7-89a8-5b24ebd40c40.png)
![tuesday](https://user-images.githubusercontent.com/13645/35175034-cec9c116-fd3f-11e7-8988-f31587cd8058.png)
![wednesday](https://user-images.githubusercontent.com/13645/35175035-cedeeca8-fd3f-11e7-81af-713f00b09671.png)

**Comment by atiaxi** [comment]
I did the thing.

**Comment by smashwilson** [comment]
![hooray](http://canacopegdl.com/images/hooray/hooray-7.jpg)
