### ISSUE TITLE
Operate on the last line of output

### ISSUE THREAD

**Issue by smashwilson** [smashwilson/pushbot#40]
It's handy to be able to give pipe-friendly commands (`pushbot elcor` and `pushbot grep`) the last line of text as input.

Doing this in Hubot won't be too bad, but getting the general-purpose pipe commands from [hubot-pipe-scripts](https://github.com/smashwilson/hubot-pipe-scripts) to respect them implicitly would be awkward.

How would a `pushbot last` command sound? That would let you do `pushbot last | pushbot grep` or `pushbot grep $(pushbot last)`.

**Comment by Tuxedocat0** [comment]
Does the recent addition of buffer make this easier to implement?

**Comment by smashwilson** [comment]
Oh hey, it totally does.
