### ISSUE TITLE
Shorter !-style commands

### ISSUE THREAD

**Issue by Tuxedocat0** [smashwilson/pushbot#45]
It would be nice to have the shorter command style like "!quote" instead of "pushbot quote".

**Comment by smashwilson** [comment]
:+1:

I'd prefer to leave the `@pushbot:` forms in there too. But I think I can :wrench: this in as an alternative.

**Comment by smashwilson** [comment]
It turns out Hubot supports an `--alias` parameter, and `!` works as a value. Well then.
