### ISSUE TITLE
!confirm, !confirmed, !unconfirm, !confirmclear

### ISSUE THREAD

**Issue by aschwa2** [smashwilson/pushbot#64]
Inspired by the truly horrible task of getting people to confirm things... confirm commands!

!confirm x - add self to list of !confirmed people for x
!unconfirm x - remove self from list of !confirmed people for x
!confirmed x - view list of all people who have run !confirm x
!confirmclear x - purge the confirm map of x

up for debate - the power to !confirm for others and to !confirmclear things that are not yours. perhaps the owner of a !confirm listing can !confirm other people.

**Comment by smashwilson** [comment]
I've shipped equivalent functionality to this with the inclusion of [hubot-plan](https://www.npmjs.com/package/hubot-plan) and its `!event ...` commands. Hopefully someone other than me will find it useful :wink:
